# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id')),
                ('num', models.CharField(max_length=100, verbose_name='值')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
